"""User with inventory field

Revision ID: 5345ff63cde6
Revises: ec401da0eb61
Create Date: 2024-09-21 21:38:29.512453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5345ff63cde6'
down_revision: Union[str, None] = 'ec401da0eb61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_inventory_id', table_name='inventory')
    # op.drop_table('inventory')
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='inventory_item_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='inventory_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='inventory_pkey')
    )
    op.create_index('ix_inventory_id', 'inventory', ['id'], unique=False)
    # ### end Alembic commands ###
